### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by abhin4v** [peterc/engblogs#11]
**What is the URL of your blog?**

https://abhinavsarkar.net/

**What is the feed URL for your blog?**

https://abhinavsarkar.net/feed.atom

**Comment by peterc** [comment]
Thank you. Just wanted to acknowledge this, am going to catch up with submissions soon.

**Comment by peterc** [comment]
We tend to shy away from personal blogs here but I will add this for now and reflect on it over the coming weeks :-) Thanks!

**Comment by abhin4v** [comment]
Hey Peter, all the posts on my blog are software related as of yet but to be future-proof, you may want to change the feed URL to https://abhinavsarkar.net/tags/programming/feed.atom. Thanks for consideration and sorry for requesting this change.

**Comment by peterc** [comment]
Updated! Thanks!
