### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by merit-mthompson** [peterc/engblogs#12]
**What is the URL of your blog?**

https://merit-network.github.io/

**What is the feed URL for your blog?**

https://merit-network.github.io/rss.xml

We're a non-profit and a lot of internal development across several teams centers around Python (Django, Celery, etc.), Docker and Oracle Database. We're planning on releasing new posts around these topics every couple weeks as a way to give back to the community and share what we learn.

**Comment by peterc** [comment]
Thank you. Just wanted to acknowledge this, am going to catch up with submissions soon.

**Comment by peterc** [comment]
It's a bit too early for this blog BUT it does look promising, so I'm going to label it as to check in a month or so and will keep this issue open for now.

**Comment by merit-mthompson** [comment]
Awesome, thanks for taking the time to check it out now and in the future! We'll get jamming on more content.
