### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by hatched** [peterc/engblogs#21]
**What is the URL of your blog?**
https://goteleport.com/blog/

**What is the feed URL for your blog?**
https://goteleport.com/blog/rss.xml

Thanks!

**Comment by peterc** [comment]
Oh I lied, the action uploaded it straight away. Fingers crossed :)

**Comment by peterc** [comment]
OK, teleport blog is now live on https://engineeringblogs.xyz/ .. I guess I engineered this a bit better than I remembered.

**Comment by hatched** [comment]
😁  Awesome, thanks!
