### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by Clarity-89** [peterc/engblogs#23]
**What is the URL of your blog?**
[https://claritydev.net/blog/](https://claritydev.net/blog/)

**What is the feed URL for your blog?**
[https://claritydev.net/rss.xml](https://claritydev.net/rss.xml)

A blog focused on front-end web development and developer productivity.

**Comment by peterc** [comment]
Thanks. I don't think it suits this collection right now, but I am going to consider it for my React newsletter instead! :)
