### ISSUE TITLE
Feed suggestions for essential frontend blogs

### ISSUE THREAD

**Issue by MajorLift** [peterc/engblogs#25]
### Microsoft: TypeScript

**What is the URL of your blog?**
https://devblogs.microsoft.com/typescript/

**What is the feed URL for your blog?**
https://devblogs.microsoft.com/typescript/feed

### Vercel: Next.js

**What is the URL of your blog?**
https://vercel.com/blog

**What is the feed URL for your blog?**
https://vercel.com/atom

### Google: Angular

**What is the URL of your blog?**
https://blog.angular.io/

**What is the feed URL for your blog?**
https://blog.angular.io/feed

### Dan Abramov (creator of React.js, Redux)

**What is the URL of your blog?**
https://overreacted.io/

**What is the feed URL for your blog?**
https://overreacted.io/rss.xml

### Daishi Kato (creator of Zustand, Jotai, Valtio)

**What is the URL of your blog?**
https://blog.axlight.com/

**What is the feed URL for your blog?**
https://blog.axlight.com/index.xml

### Matt Pocock: Total TypeScript

**What is the URL of your blog?**
https://www.totaltypescript.com/

**What is the feed URL for your blog?**
https://www.totaltypescript.com/rss.xml

### Acid Coder's Blog

**What is the URL of your blog?**
https://dev.to/tylim88/

**What is the feed URL for your blog?**
https://dev.to/feed/tylim88/

### Alice Poteat: Adventures in TypeScript

**What is the URL of your blog?**
https://code.lol/

**What is the feed URL for your blog?**
https://code.lol/index.xml

### David Walsh (ex-Mozilla)

**What is the URL of your blog?**
https://davidwalsh.name/

**What is the feed URL for your blog?**
https://davidwalsh.name/feed

### Builder.io Blog

**What is the URL of your blog?**
https://www.builder.io/blog/feed.xml

**What is the feed URL for your blog?**
https://www.builder.io/blog/

### Robin Wieruch

**What is the URL of your blog?**
https://www.robinwieruch.de/blog/

**What is the feed URL for your blog?**
https://www.robinwieruch.de/index.xml

**Comment by peterc** [comment]
Thanks!
