### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by lirantal** [peterc/engblogs#6]
👋  Peter, thanks for putting up this curated content.
I already shared on our internal #eng-learning slack for R&D :-)

An attempt to fork and contribute to the `engblogs.opml` file  resulted in GitHub 500'ing error so I'm opening this issue instead with the data you need if you'd end up considering it for the list:

**What is the URL of your blog?**
https://snyk.io/blog

**What is the feed URL for your blog?**
https://snyk.io/blog/category/engineering/feed/

**Comment by peterc** [comment]
It seems like GitHub has had a whole bunch of downtime this morning which might be part of the issue, but I'll see if I can get it added now - thanks!

**Comment by lirantal** [comment]
Thanks Peter!
