### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by stephencookdev** [peterc/engblogs#7]
Such a great feed 😊  would love to be included in the feed — mostly posting about frontend / javascript

**What is the URL of your blog?**
https://stephencook.dev/blog

**What is the feed URL for your blog?**
https://stephencook.dev/feed.xml

**Comment by peterc** [comment]
Thanks Stephen! I filter the list for feeds that don't post very frequently and am not sure your posts are frequent enough at this point with your last one being 5 months ago. Have you got any plans for some more posts in the future? I would be happy to reconsider.
