### ISSUE TITLE
Feed suggestion

### ISSUE THREAD

**Issue by mhatvan** [peterc/engblogs#8]
Hey Peter, I would love to be included in your engineering feed!

I write mostly about topics like JAMstack, Open source contributions and Svelte/Sapper. Some of my blog posts have been published on sites like HackerNoon, codeburst.io or Better Programming on Medium.

**What is the URL of your blog?**
https://markushatvan.com/

**What is the feed URL for your blog?**
https://markushatvan.com/rss.xml

**Comment by peterc** [comment]
Adding this today - thank you!
